### ISSUE TITLE
Homey Pro 2023 compatibility?

### ISSUE THREAD

**Issue by GHBU007** [mickem/medin.name.dakboard#2]
Hi,
I expect to receive my new Homey Pro soon and would like to use DAKboard, but on the Hopmey hompe page the following message is displayed:
This app is not compatible with Homey Pro (Early 2023).
This app is outdated and requires an update to work on Homey Pro (Early 2023). If you want this to happen, please contact the developer.
Will the app be updated? if yes, when do you expect it to be ready?
BR Eric

**Comment by mickem** [comment]
Yes, the moment I get my new Homey and I can test the app I will release an updated version.

**Comment by GHBU007** [comment]
Excellent, thank you for the informasjon.
Shouldn’t be long now before they ship the new pro - fingers crossed
